"""Adds columns theme_es, origin_es and en

Revision ID: cb5eb7e9710a
Revises: e8eba8ed0c00
Create Date: 2024-02-29 23:29:16.806478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb5eb7e9710a'
down_revision = 'e8eba8ed0c00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('IRA_Nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_es', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('theme_en', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('origin_es', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('origin_en', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('IRA_Nodes', schema=None) as batch_op:
        batch_op.drop_column('origin_en')
        batch_op.drop_column('origin_es')
        batch_op.drop_column('theme_en')
        batch_op.drop_column('theme_es')

    # ### end Alembic commands ###
