"""new fields in IRA_Questions model

Revision ID: e8eba8ed0c00
Revises: 0609837d2fab
Create Date: 2023-11-04 21:38:45.854439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8eba8ed0c00'
down_revision = '0609837d2fab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('IRA_Questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_question_es', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('short_question_en', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('help_es', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('help_en', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('acronym_es', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('acronym_en', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('IRA_Questions', schema=None) as batch_op:
        batch_op.drop_column('acronym_en')
        batch_op.drop_column('acronym_es')
        batch_op.drop_column('help_en')
        batch_op.drop_column('help_es')
        batch_op.drop_column('short_question_en')
        batch_op.drop_column('short_question_es')

    # ### end Alembic commands ###
